### ISSUE TITLE
can't start the script

### ISSUE THREAD

**Issue by ducpro0211kk** [sudo-do/discord-selfbot-owo-bot#11]
after i enter the channel id it stops . When I press ctrl+c it works

**Comment by ducpro0211kk** [comment]
there is one more error that i have to enter the token twice, channel id

**Comment by ducpro0211kk** [comment]
I think it logged into the account twice

**Comment by sudo-do** [comment]
um, i think thats related with multiprocessing and #7 
i'll take a look when i get back to home

btw, what os do you use?

**Comment by ducpro0211kk** [comment]
I use windows 10 and Python 3.9.6

**Comment by sudo-do** [comment]
it works on me, idfk why.
however, I'll do few big changes on release 2. hold on

**Comment by sudo-do** [comment]
please close this issue if this commit fixed the issue, else, tell me

**Comment by ducpro0211kk** [comment]
It worked. Thank you
