### ISSUE TITLE
Bot stopping suddenly for captcha when there's no captcha.

### ISSUE THREAD

**Issue by sotongboi** [sudo-do/discord-selfbot-owo-bot#30]
The bot will go smoothly, but after some time, it may stop suddenly asking for me to answer a captcha when there's none, otherwise it works fine.

**Comment by sudo-do** [comment]
ow, this project was discontinued

**Comment by sudo-do** [comment]
i don't want to drop it but i don't have time

**Comment by sudo-do** [comment]
i may return sometime idk

**Comment by sotongboi** [comment]
Not sure if this would help but it might, so I'll post it.
Normally, this issue happens when other members in the server do something in the channel that, which I think, involves embeds. The most common of OwO Bot stopping is when someone rolls Mudae in the channel, I think it's because of the embed? (I have completely no idea please forgive my ignorance) Or it might just be complete coincidence as it sometimes stop with no one saying anything in the channel too.

**Comment by sudo-do** [comment]
hm. according to the information you give this error may be related to issuechecker

**Comment by sudo-do** [comment]
contract me iressent#1007

**Comment by sudo-do** [comment]
for anyone having the same issue reviewed main.py file is attache
[updated.zip](https://github.com/sudo-do/discord-selfbot-owo-bot/files/7891456/updated.zip)
d
